
CREATE TABLE DIRECCION(ID_DIRECCION INTEGER PRIMARY KEY AUTO_INCREMENT,
              ID_USUARIO INTEGER,
              CALLE VARCHAR(250),
              CP INTEGER,
              COLONIA VARCHAR(300),
              ESTADO VARCHAR(200),
              CONSTRAINT FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO));